"use client";
// import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import AppSideBar from "./components/sidebar";
import TopLoader from "./components/toploader";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = localStorage.getItem("access_token");

  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <TopLoader />
        {token && <Navbar />}
        <div className="flex sticky top-0">
          {token && <AppSideBar />}
          <div className="bg-grey-200 flex-grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
